services:
  - type: web
    name: swankies-elite-detail
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production